config/routes.rb
Traits::Application.routes.draw do


  get '/observations/count/:model1/:itemid1', to: 'observations#count'
  get '/observations/count/:model1/:itemid1/:model2/:itemid2', to: 'observations#count'

  get '/resources/:id/doi', to: 'resources#doi'

  get '/users/:id/species', to: 'users#species'

  get '/resources/:id/duplicates', to: 'resources#duplicates'
  get '/traits/:id/duplicates', to: 'traits#duplicates', :as => :duplicates_trait
  get '/traits/:id/meta', to: 'traits#meta', :as => :meta_trait
  get '/traits/overview', to: 'traits#overview', :as => :overview_traits
  get '/traits/:id/papers', to: 'traits#resources', :as => :resources_trait
  # match '/meta/:id',     to: 'static_pages#show',    via: 'get', :as => :show_meta

  match '/resources/:id/expunge',     to: 'resources#expunge',    via: 'get', :as => :expunge_resource
  match '/resources/:id/update',     to: 'resources#update',    via: 'get', :as => :update_resource

  resources :duplicates 

  resources :releases

  # resources :observations do
  #   resources :issues
  # end

  get 'password_resets/new'

  match '/observation_imports/approve', to: 'observation_imports#approve', via: ['get', 'post'] , :as => :observation_imports_approve

  #get '/imports/show', to: 'imports#show', :as => :show_imports
  # match '/imports/approve', to: 'imports#approve', via: ['get', 'post'] , :as => :approve
  match '/imports/:name', to: 'imports#create', :via => :post, :as => :upload
  get '/imports/:name', to: 'imports#new'
  
  match '/search/json_completion', to: 'search#json_completion', via: 'get', as: 'json_completion'
  
  resources :imports
  resources :search 
  resources :synonyms

  
  get '/history', to:'versions#index'
  get '/history/:version_id', to: 'versions#show'
  post '/revert/:version_id', to: 'versions#revert_back'
  get '/species/:id/resources', to: 'species#show'
  get '/traits/:id/resources', to: 'traits#show'
  get '/locations/:id/resources', to: 'locations#show'
  get '/resources/:id/resources', to: 'resources#show'
  get '/releases/:id/resources', to: 'releases#show'

  
  get '/resources/status', to: 'resources#status'

  # match '/duplicate/:id',     to: 'static_pages#duplicate',    via: 'get', :as => :duplicate_meta
# get '/meta/:ids', to: 'static_pages#show'

  
  resources :imports

  resources :methodologies
  post '/methodology/:id/trait', to: 'methodologies#remove_trait', :as => :remove_methodology_trait
  resources :methodologies do
    post :export, :on => :collection
  end

  resources :password_resets

  resources :species do
    post :export, :on => :collection
  end

  resources :species do
    resources :traits do
      resources :users
    end
  end

  resources :locations do
    post :export, :on => :collection
  end

  resources :resources do
    post :export, :on => :collection
  end

  
  resources :standards do
    post :export, :on => :collection
  end

  resources :measurements 

  resources :issues

  resources :observation_imports

  resources :observations do  
    resources :issues

      post :update_multiple, :on => :collection
      # get :autocomplete_location_name, :on => :collection
      # get :autocomplete_specie_name, :on => :collection
      # get :autocomplete_resource_author, :on => :collection

      get :update_values, :on => :collection
      get :update_values, :on => :member
      get :update_random, :on => :collection
      get :update_random, :on => :member

  end

  #match ':controller(/:action(/:id))', via: 'get'

  # resources :users do
  #   resources :traits
  # end
  
  resources :traits do

    post :export, :on => :collection
  end

  resources :entities

  resources :users do  
      post :update_multiple, :on => :collection
  end
  
  resources :sessions,      only: [:new, :create, :destroy]


  root to: 'static_pages#home'
  match '/signup',      to: 'users#new',            via: 'get'
  match '/signin',      to: 'sessions#new',         via: 'get'
  match '/signout',     to: 'sessions#destroy',     via: 'delete'

  match '/meta',        to: 'static_pages#meta',    via: 'get'
  match '/release',        to: 'static_pages#release',    via: 'get'
  match '/uploads',        to: 'static_pages#uploads',    via: 'get'

  match '/test',  to: 'static_pages#test',   via: 'get'
  match '/procedures',  to: 'static_pages#procedures',   via: 'get'
  match '/editors',     to: 'static_pages#editors',   via: 'get'
  match '/contributors', to: 'static_pages#contributors',   via: 'get'
  match '/download',    to: 'static_pages#download',   via: 'get'
  match '/bulk_import', to: 'static_pages#bulk_import',   via: 'get'
  match '/documentation',    to: 'static_pages#documentation',   via: 'get'

  match '/export_specie_trait', to: 'static_pages#export_specie_trait',   via: 'get'
  match '/export_location_trait', to: 'static_pages#export_location_trait',   via: 'get'
  match '/export_ready_trait', to: 'static_pages#export_ready_trait',   via: 'get'

  match '/export_release_resources', to: 'static_pages#export_release_resources',   via: 'get'
  match '/export_release', to: 'static_pages#export_release',   via: 'get'

  match '/doi_new',    to: 'resources#doi_new',   via: 'get'


  # dynamic pull-down for trait select
  # match '/update_values', to: 'measurements#update_values', via: 'get'
  

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def index
		if params[:search] && params[:search] != ""
			if not params[:model_name]
				params[:model_name] = ['Specie', 'Trait', 'Location', 'Resource', 'Standard', 'Observation', 'Methodology']
			end

			@result_present = false
			@store = {}

			params[:model_name].each do |m|
				@model = m.classify.constantize
				name = m.downcase + '_search'
				puts "name: "
				puts name
				puts m

				search_result = @model.search do
					without(:hide, true) if m == "Trait"
					fulltext params[:search]

					paginate :page => 1, :per_page => 30
				end

				if not search_result.results.blank?
					@result_present = true
				end
				
				instance_variable_set("@#{name}", search_result)

				@store[m.downcase] = search_result.results.size
			end

			# Redirect if only 1 result in 1 model
			singletons = @store.select{|key, hash| hash == 1 }
			others = @store.select{|key, hash| hash > 1 }
			models = @store.select{|key, hash| hash > 0 }

			if singletons.count == 1 and others.count == 0
				puts singletons.keys
				redirect_to eval("#{singletons.keys[0]}_path(@#{singletons.keys[0]}_search.results.first, :search => params[:search])")
			elsif models.count == 1
				redirect_to eval("#{models.keys[0].pluralize}_path(:search => params[:search])")
			end

		else
			# @location_search = nil
		end
	end

	def json_completion
		model_names = ['Specie', 'Trait', 'Location', 'Resource', 'Standard', 'Methodology', 'Version']
		
		bucket = []
		model_names.each do |m|
				@model = m.classify.constantize
				name = m.downcase + '_search'
				puts "name: "
				puts name
				
				search = @model.search do
					without(:hide, true) if m == "Trait"
					fulltext params[:search]
					# keywords(params["search"])
				end

				if search.results.count > 0
					bucket << '------ ' + m.pluralize + ' ------'
					column_name = @model.column_names[1]
					bucket << search.results.map{ |x| x.attributes[column_name]}
				end
		end

		render :json => bucket.flatten
	end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	def index
		if params[:search] 
			if not params[:model_name]
				params[:model_name] = ['Location', 'Coral', 'Trait', 'Resource', 'Standard']
			end
			@result_present = false
			params[:model_name].each do |m|
				@model = m.classify.constantize
				name = m.downcase + '_search'
				puts "name: "
				puts name
				
				search_result = @model.search do
					fulltext params[:search]
				end

				if not search_result.results.blank?
					@result_present = true
				end
				instance_variable_set("@#{name}", search_result)
			end
		else
			@location_search = nil
		end
	end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<div class="col-md-3">
	<h1>Search</h1>
	<hr>
		
	<div class="ui-widget">
  	<%= form_tag search_index_path, :method => :get do %>
			<div class="form-group">
		    <%#= text_field_tag :search, params[:search],  { class: "form-control search", placeholder: "Search..." }   %>
			</div>
		    <%= hidden_field_tag :search, params[:search] %>
	    
			<div class="form-group">
		    Limit search to (optional):
		    <%= select_tag :model_name, options_for_select(['Specie', 'Trait', 'Resource', 'Location', 'Standard', 'Methodology', 'Observation'], params[:model_name]), { :multiple => true, :size =>7, class: "form-control"} %>
			</div>

	    <%= submit_tag "Search Again", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

<div class="col-md-9">

	<% if defined?(@result_present) %>
		<!-- <h4>Results...</h4> -->
	<% end %>
	
	<% if (defined?(@result_present) ) && (not @result_present )%>
		<div class="alert alert-danger">Your query did not result any results.</div>
	<% end %>

	<% if (not defined?(@result_present) ) && (not @result_present )%>
		<div class="alert alert-danger">No query entered.</div>
	<% end %>

	<% if @specie_search  %>
		<% if not @specie_search.results.blank? %>
			<h4><%= link_to "Species", species_path(search: params[:search]) %></h4>
		<% end %>
		<ul class="list-group">
			<% @specie_search.results.each do |s| %>
	     	<li class="list-group-item">							
					<%= link_to s.specie_name, s %>
					<% if s.synonyms.size > 0 %>
						<% synonyms = [] %>
						<% s.synonyms.each do |synonym| %>
				    	<% synonyms << synonym.synonym_name %>
						<% end %>
						(<%= synonyms.join(", ") %>)
					<% end %>
				</li>
			<% end %>
		</ul>
	<% end %>

	<% if @trait_search %>
		<% if not @trait_search.results.blank? %>
			<h4><%= link_to "Traits", traits_path(search: params[:search]) %></h4>
		<% end %>
		<ul class="list-group">
			<% @trait_search.results.each do |s| %>
	     	<li class="list-group-item">							
					<%= link_to s.trait_name, s %>
				</li>
			<% end %>
		</ul>
	<% end %>

	<% if @standard_search %>
		<% if not @standard_search.results.blank? %>
			<h4><%= link_to "Standards", standards_path(search: params[:search]) %></h4>
		<% end %>
		<ul class="list-group">
			<% @standard_search.results.each do |s| %>
	     	<li class="list-group-item">							
					<%= link_to s.standard_name, s %>
					<% if s.standard_unit %>
						(<%= s.standard_unit %>)
					<% end %>
				</li>
			<% end %>
		</ul>
	<% end %>


	<% if @location_search %>
		<% if not @location_search.results.blank? %>
			<h4><%= link_to "Locations", locations_path(search: params[:search]) %></h4>
		<% end %>
		<ul class="list-group">
			<% @location_search.results.each do |s| %>
	     	<li class="list-group-item">							
					<%= link_to s.location_name, s %>
					(lat: <%= s.latitude %>, lon: <%= s.longitude %>)
				</li>
			<% end %>
		</ul>
	<% end %>

	<% if @resource_search %>
		<% if not @resource_search.results.blank? %>
			<h4><%= link_to "Resources", resources_path(search: params[:search]) %></h4>
		<% end %>
		<ul class="list-group">
			<% @resource_search.results.each do |s| %>
	     	<li class="list-group-item">							
		        	<%= link_to s.author, s %>
		        	<% if s.year %>
			        	(<%= s.year %>)
	    				<% end %>		
		        	<%= s.title %>.
              <% if s.journal %>
                <em><%= s.journal %></em>
              <% end %>   
              <% if s.volume_pages %>
                <%= s.volume_pages %>
              <% end %>   
				</li>
			<% end %>
		</ul>
	<% end %>

	<% if @methodology_search %>
		<% if not @methodology_search.results.blank? %>
			<h4><%= link_to "Methodologies", methodologies_path(search: params[:search]) %></h4>
		<% end %>
		<ul class="list-group">
			<% @methodology_search.results.each do |s| %>
	     	<li class="list-group-item">							
					<%= link_to s.methodology_name, s %>
				</li>
			<% end %>
		</ul>
	<% end %>

	<% if @version_search %>
		<% if not @version_search.results.blank? %>
			<h4><%= link_to "Database versions", versions_path(search: params[:search]) %></h4>
		<% end %>
		<ul class="list-group">
			<% @version_search.results.each do |s| %>
	     	<li class="list-group-item">							
					<%= link_to s.version_notes s %>
				</li>
			<% end %>
		</ul>
	<% end %>

	<% if @observation_search %>
		<% if not @observation_search.results.blank? %>
			<h4><%= link_to "Observations", observations_path(search: params[:search]) %></h4>
		<% end %>
		<ul class="list-group">
			<% @observation_search.results.each do |s| %>
				<% s.measurements.each do |m| %>				
		     	<li class="list-group-item">							
						<%= link_to "Observation #{s.id}", s %>
						| <em><%= link_to s.specie.specie_name, specie_path(s.specie) %></em>
						<% if s.location %>
							| <%= link_to s.location.location_name, location_path(s.location) %>
						<% end %>
						| <%= link_to m.trait.trait_name, trait_path(m.trait) %> | <%= m.value %>
						<% if m.standard.standard_unit %>
							(<%= m.standard.standard_unit %>)
						<% end %>
					</li>
				<% end %>
			<% end %>
		</ul>
	<% end %>

</div>