config/routes.rb
Traits::Application.routes.draw do


  get '/observations/count/:model1/:itemid1', to: 'observations#count'
  get '/observations/count/:model1/:itemid1/:model2/:itemid2', to: 'observations#count'

  get '/resources/:id/doi', to: 'resources#doi'

  get '/users/:id/species', to: 'users#species'

  get '/resources/:id/duplicates', to: 'resources#duplicates'
  get '/traits/:id/duplicates', to: 'traits#duplicates', :as => :duplicates_trait
  get '/traits/:id/meta', to: 'traits#meta', :as => :meta_trait
  get '/traits/overview', to: 'traits#overview', :as => :overview_traits
  get '/traits/:id/papers', to: 'traits#resources', :as => :resources_trait
  # match '/meta/:id',     to: 'static_pages#show',    via: 'get', :as => :show_meta

  match '/resources/:id/expunge',     to: 'resources#expunge',    via: 'get', :as => :expunge_resource
  match '/resources/:id/update',     to: 'resources#update',    via: 'get', :as => :update_resource

  resources :duplicates 

  resources :releases

  # resources :observations do
  #   resources :issues
  # end

  get 'password_resets/new'

  match '/observation_imports/approve', to: 'observation_imports#approve', via: ['get', 'post'] , :as => :observation_imports_approve

  #get '/imports/show', to: 'imports#show', :as => :show_imports
  # match '/imports/approve', to: 'imports#approve', via: ['get', 'post'] , :as => :approve
  match '/imports/:name', to: 'imports#create', :via => :post, :as => :upload
  get '/imports/:name', to: 'imports#new'
  
  match '/search/json_completion', to: 'search#json_completion', via: 'get', as: 'json_completion'
  
  resources :imports
  resources :search 
  resources :synonyms

  
  get '/history', to:'versions#index'
  get '/history/:version_id', to: 'versions#show'
  post '/revert/:version_id', to: 'versions#revert_back'
  get '/species/:id/resources', to: 'species#show'
  get '/traits/:id/resources', to: 'traits#show'
  get '/locations/:id/resources', to: 'locations#show'
  get '/resources/:id/resources', to: 'resources#show'
  get '/releases/:id/resources', to: 'releases#show'

  
  get '/resources/status', to: 'resources#status'

  # match '/duplicate/:id',     to: 'static_pages#duplicate',    via: 'get', :as => :duplicate_meta
# get '/meta/:ids', to: 'static_pages#show'

  
  resources :imports

  resources :methodologies
  post '/methodology/:id/trait', to: 'methodologies#remove_trait', :as => :remove_methodology_trait
  resources :methodologies do
    post :export, :on => :collection
  end

  resources :password_resets

  resources :species do
    post :export, :on => :collection
  end

  resources :species do
    resources :traits do
      resources :users
    end
  end

  resources :locations do
    post :export, :on => :collection
  end

  resources :resources do
    post :export, :on => :collection
  end

  
  resources :standards do
    post :export, :on => :collection
  end

  resources :measurements 

  resources :issues

  resources :observation_imports

  resources :observations do  
    resources :issues

      post :update_multiple, :on => :collection
      # get :autocomplete_location_name, :on => :collection
      # get :autocomplete_specie_name, :on => :collection
      # get :autocomplete_resource_author, :on => :collection

      get :update_values, :on => :collection
      get :update_values, :on => :member
      get :update_random, :on => :collection
      get :update_random, :on => :member

  end

  #match ':controller(/:action(/:id))', via: 'get'

  # resources :users do
  #   resources :traits
  # end
  
  resources :traits do

    post :export, :on => :collection
  end

  resources :entities

  resources :users do  
      post :update_multiple, :on => :collection
  end
  
  resources :sessions,      only: [:new, :create, :destroy]


  root to: 'static_pages#home'
  match '/signup',      to: 'users#new',            via: 'get'
  match '/signin',      to: 'sessions#new',         via: 'get'
  match '/signout',     to: 'sessions#destroy',     via: 'delete'

  match '/meta',        to: 'static_pages#meta',    via: 'get'
  match '/release',        to: 'static_pages#release',    via: 'get'
  match '/uploads',        to: 'static_pages#uploads',    via: 'get'

  match '/test',  to: 'static_pages#test',   via: 'get'
  match '/procedures',  to: 'static_pages#procedures',   via: 'get'
  match '/editors',     to: 'static_pages#editors',   via: 'get'
  match '/contributors', to: 'static_pages#contributors',   via: 'get'
  match '/download',    to: 'static_pages#download',   via: 'get'
  match '/bulk_import', to: 'static_pages#bulk_import',   via: 'get'
  match '/documentation',    to: 'static_pages#documentation',   via: 'get'

  match '/export_specie_trait', to: 'static_pages#export_specie_trait',   via: 'get'
  match '/export_location_trait', to: 'static_pages#export_location_trait',   via: 'get'
  match '/export_ready_trait', to: 'static_pages#export_ready_trait',   via: 'get'

  match '/export_release_resources', to: 'static_pages#export_release_resources',   via: 'get'
  match '/export_release', to: 'static_pages#export_release',   via: 'get'

  match '/doi_new',    to: 'resources#doi_new',   via: 'get'


  # dynamic pull-down for trait select
  # match '/update_values', to: 'measurements#update_values', via: 'get'
  

end

app/models/trait.rb
class Trait < ActiveRecord::Base
  belongs_to :standard
  belongs_to :user
  has_paper_trail
  
  has_many :measurements, :dependent => :destroy
  validates :trait_name, :presence => true
  validates :trait_name, :uniqueness => true
  validates :standard_id, :presence => true
  
  has_many :traitvalues, :dependent => :destroy

  # has_and_belongs_to_many :methodologies, :dependent => :destroy
  # accepts_nested_attributes_for :methodologies, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :traitvalues, :reject_if => :all_blank, :allow_destroy => true
  
  default_scope -> { order('trait_class ASC') }

  scope :editor, lambda {|ed| where("user_id = ?", ed)}

  searchable do
    text :trait_name
    text :trait_class
    boolean :hide
    string :trait_class_sortable do 
      trait_class
    end
  end

  '''
  def self.search(search)
    if search
      where("trait_name LIKE ? OR trait_class LIKE ?", "%#{search}%", "%#{search}%")
    else
      all
    end
  end  
  '''
end

app/controllers/traits_controller.rb
class TraitsController < ApplicationController

  # before_action :signed_in_user
  before_action :editor, except: [:index, :show, :export]
  before_action :set_trait, only: [:show, :edit, :update, :destroy, :duplicates, :meta, :resources]
  before_action :admin_user, only: :destroy

  skip_before_action :verify_authenticity_token, :only => [:update]

  # GET /traits
  # GET /traits.json
  def index

    if params[:trait_class] and params[:trait_class].blank?
      params[:trait_class].delete
    end
    
    @search = Trait.search do
      fulltext params[:search]

      if params[:trait_class] and params[:trait_class].present?
        with :trait_class_sortable, params[:trait_class]
        paginate page: params[:page], per_page: 9999
      end

      order_by :trait_class_sortable, :asc
      
      if params[:all]
        paginate page: params[:page], per_page: 9999
      else
        paginate page: params[:page]
      end
    end
    @traits = @search.results

    respond_to do |format|
      format.html
      format.csv { send_data Trait.all.to_csv }
    end    
  end

  def resources
    
    @resources = Resource.where("id IN (?)", Observation.joins(:measurements).where("trait_id = ?", @trait.id).map(&:resource_id).uniq)

    respond_to do |format|
      format.html
      # format.csv { send_data Trait.all.to_csv }
    end    
  end


  def overview

    query = Trait.all
    query = query.where(:release_status => params[:release_status]) if not params[:release_status].blank?
    @traits = query.all

    respond_to do |format|
      format.html
    end    
  end

  def export
    if params[:checked]
      @observations = Observation.joins(:measurements).where(:measurements => {:trait_id => params[:checked]})
      @observations = observation_filter(@observations, true, params[:release])
    else
      @observations = []
    end

    send_zip(@observations, params[:taxonomy], params[:contextual], params[:global])
  end

  def show

    if params[:specie_id]
      @specie = Specie.find(params[:specie_id])
      @observations = Observation.includes(:specie).joins(:measurements).where('observations.specie_id = ? AND measurements.trait_id = ?', @specie.id, @trait.id)
    else
      @observations = Observation.joins(:measurements).where('measurements.trait_id = ?', @trait.id)
    end

    if params[:value]
      @observations = @observations.joins(:measurements).where('measurements.value = ?', params[:value])
    end

    if @trait.traitvalues.present?
      @mea_traitvalues = Measurement.where('trait_id = ?', @trait.id).map(&:value).uniq
      @rec_traitvalues = @trait.traitvalues.map(&:value_name).uniq
    end

    @observations = observation_filter(@observations, true)

    @methodologies = Methodology.where(:id => Measurement.where("observation_id IN (?) AND trait_id = ?", @observations.map(&:id), @trait.id).map(&:methodology_id))

    @standards = Standard.where(:id => Measurement.where("observation_id IN (?) AND trait_id = ?", @observations.map(&:id), @trait.id).map(&:standard_id))
    
    data_table = GoogleVisualr::DataTable.new

    puts @trait.standard

    if @trait.standard
      if @trait.standard.standard_unit != "id" && @trait.standard.standard_unit != "text"
        if @trait.standard.standard_class == "Nominal class" || @trait.standard.standard_name == "Category" || @trait.standard.standard_name == "Binomial"
          data_table.new_column('string')
          data_table.new_column('number')

          @trait.measurements.collect(&:value).uniq.each do |i|
            data_table.add_row([i, @trait.measurements.where("value LIKE ?", i).size])
          end

  #        data_table.sort(1)

          option = { width: 250, height: 250, legend: 'none' }
          @chart = GoogleVisualr::Interactive::PieChart.new(data_table, option)
        else
          data_table.new_column('number')

          p = 0
          # @trait.measurements.map(&:value).map{|v| v.to_d}.sort.reverse.each do |i|
          @trait.measurements.each do |i|
            if @trait.log_data
              data_table.add_row([Math.log10(i.value.to_d)])
            else
              data_table.add_row([i.value.to_d])
            end
          end

          if @trait.log_data
            option = { width: 250, height: 250, legend: 'none', :vAxis => { :title => "Frequency" }, :hAxis => { :title => "#{@trait.trait_name} (#{@trait.standard.standard_unit}), log10" } }
          else
            option = { width: 250, height: 250, legend: 'none', :vAxis => { :title => "Frequency" }, :hAxis => { :title => "#{@trait.trait_name} (#{@trait.standard.standard_unit})" } }
          end

          @chart = GoogleVisualr::Interactive::Histogram.new(data_table, option)
          # @chart.add_listener("select", "function(e) { EventHandler(e, chart, data_table) }")
        end
     end
   end
    # @data_table = data_table

    respond_to do |format|
      format.html { @observations = @observations.paginate(page: params[:page]) }
      format.csv { download_observations(@observations, params[:taxonomy], params[:contextual] || "on", params[:global]) }
      format.zip{ send_zip(@observations, params[:taxonomy], params[:contextual] || "on", params[:global]) }
    end

  end

  def meta
    # params[:editor] = "ready_for_release" if params[:status].blank?
    query = Trait.all
    query = query.editor(params[:editor]) if not params[:editor].blank?
    query = query.where(:release_status => params[:release_status]) if not params[:release_status].blank?
    @traits = query.all
  end

  def meta
    # @trait = Trait.find(params[:id])
  end

  def duplicates

    @duplicates = Observation.joins(:measurements).select("specie_id, resource_id, location_id, trait_id, standard_id, value, array_agg(observation_id) as ids").where("trait_id = ?", params[:id]).where("trait_id NOT IN (?) AND value_type != 'raw_value'", Trait.where("trait_class = 'Contextual'").map(&:id)).group(:specie_id, :resource_id, :location_id, :trait_id, :standard_id, :value).having("count(*) > 1")

    respond_to do |format|
      format.html { }
      format.json { 
        render json: { dups: @duplicates.length }
      }
    end
  end

  # GET /traits/new
  def new
    @trait = Trait.new
  end

  # GET /traits/1/edit
  def edit
  end

  # POST /traits
  # POST /traits.json
  def create
    @trait = Trait.new(trait_params)
    # methodology_ids =  params[:trait][:methodologies_attributes]
    traitvalue_ids =  params[:trait][:traitvalues_attributes]

    # if not methodology_ids.nil?
    #   methodology_ids.keys().each do |k|
    #     methodology = Methodology.find(methodology_ids[k]["id"])
    #     @trait.methodologies << methodology if methodology_ids[k]["_destroy"] != "1" and not @trait.methodologies.include? methodology
    #   end
    # end

    if @trait.save
      redirect_to @trait, flash: {success: "Trait was successfully created." }
    else
      render action: 'new' 
    end
  end

  # PATCH/PUT /traits/1
  # PATCH/PUT /traits/1.json
  def update
    # methodology_ids =  params[:trait][:methodologies_attributes]
    traitvalue_ids =  params[:trait][:traitvalues_attributes]

    # @trait.methodologies.delete_all()
    #@trait.traitvalues.delete_all()

    # if not methodology_ids.nil?
    #   methodology_ids.keys().each do |k|
    #     method = Methodology.find(methodology_ids[k]["id"])
    #     @trait.methodologies << method if ((methodology_ids[k]["_destroy"] != "1") and (not @trait.methodologies.include? method))
        
    #   end
    # end
    
    
    if @trait.update(trait_params)
      redirect_to @trait, flash: {success: "Trait was successfully updated." }
    else
      render action: 'edit'
    end
  end

  # DELETE /traits/1
  # DELETE /traits/1.json
  def destroy
    @trait.destroy
    respond_to do |format|
      format.html { redirect_to traits_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trait
      @trait = Trait.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trait_params
      params.require(:trait).permit(:trait_name, :trait_description, :trait_class, :value_range, :standard_id, :user_id, :approval_status, :release_status, :methodologies, :hide, :log_data, traitvalues_attributes: [:id, :value_name, :value_description, :_destroy])
    end
end

app/helpers/traits_helper.rb
module TraitsHelper
end

app/views/traits/duplicates.html.erb
<% provide(:title, 'Duplicates | ' + @trait.trait_name) %>

<div class="col-md-12">
  <h1>
    <% if @trait.trait_class == "Contextual" %>
      <span class="glyphicon glyphicon-eye-open" data-toggle="tooltip" data-placement="top" title="Contextual trait"></span>
    <% end %>
    <%= @trait.trait_name %>
    <span class="label label-danger pull-right">duplicates</span>

  </h1>
  <hr>

  <p>
    <div class="btn-group">
      <%= link_to 'Back', trait_path(@trait), class: "btn btn-xs btn-default" %>
    </div>
    <div class="btn-group">
      <% if signed_in? && current_user.editor? %>
        <%= link_to "Meta", meta_trait_path(@trait), class: "btn btn-default btn-xs" %>
        <%= link_to "Duplicates", duplicates_trait_path(@trait), class: "btn btn-default btn-xs active" %>
        <%= link_to "Resources", resources_trait_path(@trait), class: "btn btn-default btn-xs" %>
        <%= link_to "Overview", overview_traits_path(:release_status => 'ready_for_release'), class: "btn btn-default btn-xs" %>
      <% end %>
    </div>
  </p>

  <p>
    <span class="label label-warning"><%= @duplicates.length %></span> potential duplicate records have been detected for this trait. Detection occurs when an observation occurs of the same species, resource and location with the same measured trait, standard and value. Duplicates might be legitimate.
  </p>

  <% if @duplicates %>
    <ul class="list-group">
      <% @duplicates.order(:specie_id).each do |dup| %>

        <li class="list-group-item">             
          <div class="row">
            <div class="col-sm-1">
              <% dup.ids.each do |id| %>
                <%= link_to id, observation_path(id), class: "label label-default" %>
              <% end %>
            </div>
            <div class="col-sm-2">
              <em><%= link_to Specie.select(:specie_name).find_by_id(dup.specie_id).specie_name, specie_path(dup.specie_id) %></em>
            </div>
            <div class="col-sm-3">
              <%= link_to Resource.select(:author).find_by_id(dup.resource_id).author, resource_path(dup.resource_id) %>
            </div>
            <div class="col-sm-2">
              <%= dup.value %>
            </div>
            <div class="col-sm-2">
              <% standard = Standard.select(:standard_name, :standard_unit).find_by_id(dup.standard_id) %>
              <%= link_to standard.standard_unit, standard_path(dup.standard_id) %> (<%= standard.standard_name %>)
            </div>
            <div class="col-sm-2">
              <%= link_to "Show", specie_trait_path(dup.specie_id, dup.trait_id), class: "btn btn-default btn-xs pull-right" %></p>
            </div>
          </div>

        </li>
      <% end %>
    </ul>
  <% else %>
    None
  <% end %>
  
</div>

app/views/traits/overview.html.erb
<% provide(:title, 'Traits Overview') %>

<div class="col-md-12">
	<h1>
		Traits
    <span class="label label-danger pull-right">overview</span>
	</h1>
	<hr>

	<% obs = Observation.where("private='0' AND (resource_id IS NULL OR resource_id = ?)", 0) %>
	<% if !obs.blank? %>
		<ul class="list-group">

		  <li class="list-group-item">							
				<div class="row">
					<div class="col-md-4" style="text-align:right;">
						<strong>Public observations with no resource:</strong>
						<br><span class="label label-danger">critical</span>
					</div>
					<div class="col-md-8">
						<% obs.each do |o| %>
							<%= link_to o.id, observation_path(o.id), class: "label label-default" %>
						<% end %>
					</div>
				</div>
			</li>
		</ul>
	<% end %>


	<div class="row">
		<div class="col-md-2">
			<%= form_tag overview_traits_path, :method => 'get' do %>
			  <%= select_tag :release_status, options_for_select(Trait.all.map(&:release_status).uniq, params[:release_status]), include_blank: true, onchange: "$(this).parent('form').submit();", class: "form-control" %>
			<% end %>
		</div>
	</div>

	<p>
		<span class="badge"><%= @traits.size %></span> traits
	</p>

	<%= form_tag export_traits_path do %>
    <%= hidden_field_tag :release, :value => true %>

  	<% if params[:release_status] == 'ready_for_release' %>
			<div class="row">
				<div class="col-md-12">
					<ul class="list-group">
					  <li class="list-group-item">							
							<%= link_to 'Species-trait matrix', '/export_specie_trait', :action => 'export_specie_trait', class: "btn btn-default" %>
							<%= link_to 'Location-trait matrix', '/export_location_trait', :action => 'export_location_trait', class: "btn btn-default" %>
							<%= link_to 'Overview table', '/export_ready_trait', :action => 'export_ready_trait', class: "btn btn-default" %>
							<%= link_to 'Export release data', '/export_release', :action => 'export_release', class: "btn btn-success" %>
							<%= link_to 'Export release resources', '/export_release_resources', :action => 'export_release_resources', class: "btn btn-success" %>
							<%#= submit_tag "Download Release", {class: "btn btn-success pull-right"} %>
						</li>
					</ul>
				</div>
			</div>
		<% end %>


		<ul class="list-group">
		  <li class="list-group-item">							
				<div class="row">
					<div class="col-md-2">
				  </div>
					<div class="col-md-3">
					  <strong>Description</strong>
				  </div>
					<div class="col-md-1">
					  <strong>Standard</strong>
				  </div>
					<div class="col-md-2">
					  <strong>Value range</strong>
				  </div>
					<div class="col-md-2">
					  <strong>Resources</strong>
				  </div>
					<div class="col-md-2">
					  <strong>Measurements</strong>
				  </div>
				</div>
			</li>
			
			<% @traits.sort_by{ |h| h[:release_status] }.each do |trait| %>
			  <li class="list-group-item">							
					<div class="row">
						<div class="col-md-2">
					  	<%= trait.id %>.
					  	<%= link_to trait.trait_name, trait_path(trait), 'data-no-turbolink' => true %><br>
						  <span class="label label-default"><%= trait.trait_class %></span><br>
					  	(<%= trait.user.name %>)<br>
						  <%= link_to 'Edit', edit_trait_path(trait), class: "btn btn-default btn-xs" %>
							<%= link_to "Meta", meta_trait_path(trait), class: "btn btn-default btn-xs" %>
							<%= link_to "Duplicates", duplicates_trait_path(trait), class: "btn btn-default btn-xs" %>
							<%= link_to "Resources", resources_trait_path(trait), class: "btn btn-default btn-xs" %>

					  </div>
						<div class="col-md-3">
						  <%= trait.trait_description %>
					  </div>
						<div class="col-md-1">
						  <%= trait.standard.standard_name %> (<%= trait.standard.standard_unit %>)
					  </div>
						<div class="col-md-2">
						  <% trait.traitvalues.each do |v| %>
						  	<span class="label label-primary"><%= v.value_name %></span>
							<% end %>
							<% if trait.standard.id != 2 && trait.standard.id != 10 && trait.standard.id != 40 %>
						  	<span class="label label-success">not applicable</span>
							<% end %>

					  </div>
						<div class="col-md-3">
						  <%= Observation.where("private IS false AND observations.id IN (?)", Measurement.where(:trait_id => trait.id).map(&:observation_id)).map(&:resource_id).uniq.join(", ") %>
					  </div>
						<div class="col-md-1">
						  <%= Measurement.where("trait_id = ?", trait.id).joins(:observation).where("private IS false").size %>
					  </div>
<!-- 						<div class="col-md-1">
						  <%#= check_box_tag "checked[]", trait.id, checked = true %>
					  </div> -->
				  </div>
			  </li>
			<% end %>

		<% end %>

	</ul>		

</div>

app/views/traits/show.html.erb
<% provide(:title, @trait.trait_name) %>

<div class="col-md-12">
	<h1>
		<% if @trait.trait_class == "Contextual" %>
  		<span class="glyphicon glyphicon-eye-open" data-toggle="tooltip" data-placement="top" title="Contextual trait"></span>
		<% end %>
		<%= @trait.trait_name %>
		<% if @specie %>
			(<em><%= link_to @specie.specie_name, specie_path(@specie) %></em>)
		<% end %>
	  <% if @trait.hide %>
      <span class="label label-danger pull-right" data-toggle="tooltip" data-placement="left" title="Trait only visible to Editors">hidden</span>
	  <% end %>

	</h1>
</div>

<div class="col-md-8">
  <p>
    <strong>ID:</strong>
    	<%= @trait.id %>
  </p>

	<p>
	  <strong>Class:</strong>
		<% if @trait.trait_class.present? %>
	  	<%= @trait.trait_class %>
		<% else %>
			<font style="color:lightgrey;">Unclassified</font>
		<% end %>
	</p>

  <%= render "shared/description", :description => @trait.trait_description %>

	<p>
		<strong>Standards:</strong>
		<% if not @standards.empty? %>
				<ul>
					<% @standards.each do |standard| %>
						<li>
							<%= link_to standard.standard_name, standard %> (<%= standard.standard_unit %>)
							<% if standard == @trait.standard %>
								<span class="label label-primary">default</span>
							<% end %>
					</li>
					<% end %>
				</ul>
		<% else %>
			<font style="color:lightgrey;">None entered</font>
		<% end %>
	</p>


	<% if @trait.traitvalues.present? %>
		<% @all_traitvalues = (@mea_traitvalues + @rec_traitvalues).uniq %>
		<p>
			<strong>Values:</strong>
			<% @all_traitvalues.each do |tv| %>
				<% vd = @trait.traitvalues.where(:value_name => tv) %>
      	<% if vd.present?  %>
					<span data-toggle="tooltip" data-placement="top" title="<%= vd.first.value_description %>">
				<% else %>
					<span data-toggle="tooltip" data-placement="top" title="No description">
				<% end %>

          <% if @rec_traitvalues.include?(tv) and @mea_traitvalues.include?(tv)  %>
          	<% if params[:value]  %>
	          	<% if params[:value] == tv  %>
		            <%= link_to tv, trait_path(@trait), class: "label label-primary" %>
							<% else %>
		            <%= link_to tv, trait_path(@trait, :value => tv), class: "label label-default" %>
							<% end %>
						<% else %>
	            <%= link_to tv, trait_path(@trait, :value => tv), class: "label label-primary" %>
						<% end %>
					<% else %>
						<% if !@mea_traitvalues.include?(tv) %>
		          	<%#= link_to tv, trait_path(@trait, :value => tv), class: "label label-success" %>
	          	<% if params[:value] %>
		          	<% if params[:value] == tv  %>
			          	<%= link_to tv, trait_path(@trait), class: "label label-success" %>
								<% else %>
			            <%= link_to tv, trait_path(@trait, :value => tv), class: "label label-default" %>
								<% end %>
							<% else %>
	            	<%= link_to tv, trait_path(@trait, :value => tv), class: "label label-success" %>
							<% end %>
						<% end %>
						<% if !@rec_traitvalues.include?(tv) %>
		          <%#= link_to tv, trait_path(@trait, :value => tv), class: "label label-danger" %>
	          	<% if params[:value] %>
		          	<% if params[:value] == tv  %>
			          	<%= link_to tv, trait_path(@trait), class: "label label-danger" %>
								<% else %>
			            <%= link_to tv, trait_path(@trait, :value => tv), class: "label label-default" %>
								<% end %>
							<% else %>
	            	<%= link_to tv, trait_path(@trait, :value => tv), class: "label label-danger" %>
							<% end %>
						<% end %>
					<% end %>
				</span>
			<% end %>
		</p>
	<% end %>

	<p>
		<strong>Methodologies:</strong>
		<% if not @methodologies.empty? %>
				<ul>
					<% @methodologies.each do |methodology| %>
						<li>
							<%= link_to methodology.methodology_name, methodology %>
					</li>
					<% end %>
				</ul>
		<% else %>
			<font style="color:lightgrey;">None entered</font>
		<% end %>
	</p>

	<p>
		<strong>Editor:</strong>
		<% if !@trait.user.blank? %>
			<%= @trait.user.name %> <%= @trait.user.last_name %> (<%= mail_to @trait.user.email, "contact", {:subject => "#{ENV["SITE_NAME"]} enquiry"} %>)
		<% end %>
	</p>

	<p>
		<div class="btn-group">
    	<%= link_to 'Back', traits_path, class: "btn btn-xs btn-default" %>
	  </div>
		<div class="btn-group">
			<% if signed_in? && current_user.contributor? %>
	      <%= link_to 'Edit', edit_trait_path(@trait), class: "btn btn-xs btn-default" %>
		  <% end %>
			<% if signed_in? && current_user.editor? %>
					<%= link_to "Meta", meta_trait_path(@trait), class: "btn btn-default btn-xs" %>
					<%= link_to "Duplicates", duplicates_trait_path(@trait), class: "btn btn-default btn-xs" %>
					<%= link_to "Resources", resources_trait_path(@trait), class: "btn btn-default btn-xs" %>
					<%#= link_to "Overview", overview_traits_path(:release_status => 'ready_for_release'), class: "btn btn-default btn-xs" %>
			<% end %>
	  </div>
	  <% if signed_in? && current_user.admin? %>
	    <div class="btn-group pull-right">
	      <%= link_to 'Delete', @trait, method: :delete, data: { confirm: 'Delete entire trait, including observations and measurements?' }, class: "btn btn-xs btn-danger" %>
	    </div>
		<% end %>
	</p>
  
</div>

<div class="col-md-4">
	<% if @chart %>
		<ul class="list-group">
			<li class="list-group-item">							
				<div id='chart'></div>
				<%= render_chart @chart, 'chart' %>
				<%#= @data_table %>
			</li>
		</ul>
	<% end %>
</div>

<div class="col-md-12">

	<h3>Observations</h3>

	<% if @observations.empty? %>
		<%= render "shared/no_observations" %>
	<% else %>
		<%= will_paginate @observations, :inner_window => 1, :outer_window => 0 %>
		<%= render "shared/observations" %>
		<br>
		<%= will_paginate @observations, :inner_window => 1, :outer_window => 0 %>
	<% end %>
</div>