config/routes.rb
Traits::Application.routes.draw do


  get '/observations/count/:model1/:itemid1', to: 'observations#count'
  get '/observations/count/:model1/:itemid1/:model2/:itemid2', to: 'observations#count'

  get '/resources/:id/doi', to: 'resources#doi'

  get '/users/:id/species', to: 'users#species'

  get '/resources/:id/duplicates', to: 'resources#duplicates'
  get '/traits/:id/duplicates', to: 'traits#duplicates', :as => :duplicates_trait
  get '/traits/:id/meta', to: 'traits#meta', :as => :meta_trait
  get '/traits/overview', to: 'traits#overview', :as => :overview_traits
  get '/traits/:id/papers', to: 'traits#resources', :as => :resources_trait
  # match '/meta/:id',     to: 'static_pages#show',    via: 'get', :as => :show_meta

  match '/resources/:id/expunge',     to: 'resources#expunge',    via: 'get', :as => :expunge_resource
  match '/resources/:id/update',     to: 'resources#update',    via: 'get', :as => :update_resource

  resources :duplicates 

  resources :releases

  # resources :observations do
  #   resources :issues
  # end

  get 'password_resets/new'

  match '/observation_imports/approve', to: 'observation_imports#approve', via: ['get', 'post'] , :as => :observation_imports_approve

  #get '/imports/show', to: 'imports#show', :as => :show_imports
  # match '/imports/approve', to: 'imports#approve', via: ['get', 'post'] , :as => :approve
  match '/imports/:name', to: 'imports#create', :via => :post, :as => :upload
  get '/imports/:name', to: 'imports#new'
  
  match '/search/json_completion', to: 'search#json_completion', via: 'get', as: 'json_completion'
  
  resources :imports
  resources :search 
  resources :synonyms

  
  get '/history', to:'versions#index'
  get '/history/:version_id', to: 'versions#show'
  post '/revert/:version_id', to: 'versions#revert_back'
  get '/species/:id/resources', to: 'species#show'
  get '/traits/:id/resources', to: 'traits#show'
  get '/locations/:id/resources', to: 'locations#show'
  get '/resources/:id/resources', to: 'resources#show'
  get '/releases/:id/resources', to: 'releases#show'

  
  get '/resources/status', to: 'resources#status'

  # match '/duplicate/:id',     to: 'static_pages#duplicate',    via: 'get', :as => :duplicate_meta
# get '/meta/:ids', to: 'static_pages#show'

  
  resources :imports

  resources :methodologies
  post '/methodology/:id/trait', to: 'methodologies#remove_trait', :as => :remove_methodology_trait
  resources :methodologies do
    post :export, :on => :collection
  end

  resources :password_resets

  resources :species do
    post :export, :on => :collection
  end

  resources :species do
    resources :traits do
      resources :users
    end
  end

  resources :locations do
    post :export, :on => :collection
  end

  resources :resources do
    post :export, :on => :collection
  end

  
  resources :standards do
    post :export, :on => :collection
  end

  resources :measurements 

  resources :issues

  resources :observation_imports

  resources :observations do  
    resources :issues

      post :update_multiple, :on => :collection
      # get :autocomplete_location_name, :on => :collection
      # get :autocomplete_specie_name, :on => :collection
      # get :autocomplete_resource_author, :on => :collection

      get :update_values, :on => :collection
      get :update_values, :on => :member
      get :update_random, :on => :collection
      get :update_random, :on => :member

  end

  #match ':controller(/:action(/:id))', via: 'get'

  # resources :users do
  #   resources :traits
  # end
  
  resources :traits do

    post :export, :on => :collection
  end

  resources :entities

  resources :users do  
      post :update_multiple, :on => :collection
  end
  
  resources :sessions,      only: [:new, :create, :destroy]


  root to: 'static_pages#home'
  match '/signup',      to: 'users#new',            via: 'get'
  match '/signin',      to: 'sessions#new',         via: 'get'
  match '/signout',     to: 'sessions#destroy',     via: 'delete'

  match '/meta',        to: 'static_pages#meta',    via: 'get'
  match '/release',        to: 'static_pages#release',    via: 'get'
  match '/uploads',        to: 'static_pages#uploads',    via: 'get'

  match '/test',  to: 'static_pages#test',   via: 'get'
  match '/procedures',  to: 'static_pages#procedures',   via: 'get'
  match '/editors',     to: 'static_pages#editors',   via: 'get'
  match '/contributors', to: 'static_pages#contributors',   via: 'get'
  match '/download',    to: 'static_pages#download',   via: 'get'
  match '/bulk_import', to: 'static_pages#bulk_import',   via: 'get'
  match '/documentation',    to: 'static_pages#documentation',   via: 'get'

  match '/export_specie_trait', to: 'static_pages#export_specie_trait',   via: 'get'
  match '/export_location_trait', to: 'static_pages#export_location_trait',   via: 'get'
  match '/export_ready_trait', to: 'static_pages#export_ready_trait',   via: 'get'

  match '/export_release_resources', to: 'static_pages#export_release_resources',   via: 'get'
  match '/export_release', to: 'static_pages#export_release',   via: 'get'

  match '/doi_new',    to: 'resources#doi_new',   via: 'get'


  # dynamic pull-down for trait select
  # match '/update_values', to: 'measurements#update_values', via: 'get'
  

end

app/views/shared/_access_counts.html.erb
<span class="label label-success" data-toggle="tooltip" data-placement="top" title="Number of public observations"><span class="glyphicon glyphicon-ok-circle" style="color:white;"></span> <span class="pubcount" data-itemid1=<%= itemid1 %> data-model1=<%= params[:controller] %>><span class="glyphicon glyphicon-refresh spinning"></span></span></span>

<% if signed_in? && current_user.contributor? %>
	<span class="label label-danger" data-toggle="tooltip" data-placement="top" title="Private observations"><span class="glyphicon glyphicon-remove-circle" style="color:white;"></span> <span class="pricount" data-itemid1=<%= itemid1 %> data-model1=<%= params[:controller] %>><span class="glyphicon glyphicon-refresh spinning"></span></span></span>
<% end %>

app/views/shared/_description.erb
<p>
  <strong>Description:</strong>
  <% if description.present? %>
      <%= markdown description %>
  <% else %>
    <font style="color:lightgrey;">Not entered</font>
  <% end %>
</p>

app/views/shared/_download_options.html.erb
<ul class="list-group">
	<li class="list-group-item">							
		<div class="row">
      <div class="col-md-12">
				<%= submit_tag "Download", {class: "btn btn-success pull-right"} %>
				<br><br>
				<small>
					<span class="pull-right">Include taxonomic detail? <input type="checkbox", name="taxonomy" /></span>
					<br><span class="pull-right">Include contexual data? <input type="checkbox", name="contextual", checked /></span>
					<% if not @locations %>
						<br><span class="pull-right">Global estimates only? <input type="checkbox", name="global" /></span>
					<% end %>
					<br><span class="pull-right">Check items below <span class="glyphicon glyphicon-arrow-down" style="color:grey;"></span></span>
				</small>
			</div>
		</div>
	</li>
</ul>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.full_messages.uniq.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.uniq.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_index_header.html.erb
<% model = request.original_url.split("/").last.split("?").first %>
<h1><%= model.capitalize %></h1>

<div class="btn-group pull-left">
  <% if params[:all] %>
  	<%= link_to "Paginate", "#{model}", class: "btn btn-default" %>
  <% else %>
  	<%= link_to "Show All", "#{model}?all=true", class: "btn btn-default" %>
  <% end %>
</div>
<% if model == "traits" %>  
  <div class="col-xs-3">
    <%= form_tag traits_path, :method => 'get' do %>
      <div class="form-group">
        <%= select_tag :trait_class, options_for_select(Trait.all.map(&:trait_class).uniq.reject! { |c| c.blank? }, params[:trait_class]), :onchange => "this.form.submit();", :prompt => "Subset by class...", class: "form-control" %>
      </div>
    <% end %>
  </div>
<% end %>

<div class="btn-group pull-right">
  <% if model == "locations" or model == "resources" or model == "standards" or model == "methodologies" %>  
    <% if signed_in? and current_user.contributor? %>  
      <%= link_to "New #{model.singularize.capitalize}", "#{model}/new", class: "btn btn-primary" %>
    <% end %>
    <% if model == "resources" and signed_in? && current_user.admin? %>
      <%= link_to "Order by Counts", resources_path(:count => true, :search => params[:search]), class: "btn btn-default" %>
    <% end %>

  <% elsif model == "traits" %>
    <% if signed_in? and current_user.editor? %>  
      <%= link_to "New #{model.singularize.capitalize}", "#{model}/new", class: "btn btn-primary" %>
    <% elsif signed_in? and current_user.contributor? %>
      <div data-toggle="tooltip" data-placement="bottom" title="Contact an Editor to add a new trait (see Procedures)">
        <%= link_to "New #{model.singularize.capitalize}", "#{model}/new", class: "btn btn-primary disabled" %>
      </div>
    <% end %>
    <% if signed_in? and current_user.admin? %>  
      <%= link_to "Overview", overview_traits_path(:release_status => 'ready_for_release'), class: "btn btn-default" %>
    <% end %>
  <% elsif model == "species" %>
    <% if signed_in? and current_user.admin? %>  
      <%= link_to "New #{model.capitalize}", "#{model}/new", class: "btn btn-primary" %>
    <% elsif signed_in? and current_user.contributor? %>
      <div data-toggle="tooltip" data-placement="bottom" title="Contact a Taxonomic Editor to add a new species (see Procedures)">
        <%= link_to "New #{model.capitalize}", "#{model}/new", class: "btn btn-primary disabled" %>
      </div>
    <% end %>
  <% elsif model == "releases" %>
    <% if signed_in? and current_user.admin? %>  
      <%= link_to "New #{model.singularize.capitalize}", "#{model}/new", class: "btn btn-primary" %>
    <% end %>
  <% end %>
</div>

<br><br>

app/views/shared/_instructions.html.erb
<p>Data listed below can be downloaded using the checkboxes and clicking <label class="label label-success">Download</label>. Only public trait observations (and your own private observations) will be downloaded. <label class="label label-warning">See All</label> removes pagination for cross-page viewing and download selections, but may load a little slower.</p>

app/views/shared/_no_observations.html.erb
<ul class="list-group">
  <li class="list-group-item">
    <span class="glyphicon glyphicon-remove-circle" style="color:red;"></span> None available
  </li>
</ul>

app/views/shared/_observations.html.erb
<% mark = "" %>

<% @observations.each do |obs| %>    

  <%#= obs.measurements.inspect %>
  
	<% if @user %>
		<%= hidden_field_tag "all_ids[]", obs.id %>
	<% end %>

	<% if obs.specie.specie_name != mark %>
		</ul>
		<h4><em><%= link_to obs.specie.specie_name, "/species/" + obs.specie_id.to_s %></em></h4>
		<ul class="list-group">
	<% end %>

  <% if @trait && @trait.hide %>
    <li class="list-group-item disabled">             
  <% else %>
    <li class="list-group-item">             
  <% end %>

		<div class="row">
			<div class="col-sm-1">
				<label class="checkbox-inline">

					<% if @user %>
						<%= check_box_tag "pub_ids[]", obs.id, !obs.private %>
					<% end %>

					<% if obs.private == true %>
						<span class="glyphicon glyphicon-remove-circle" style="color:red;"></span>
					<% else %>
						<span class="glyphicon glyphicon-ok-circle" style="color:green;"></span>
					<% end %>
				</label>
  		</div>

      <div class="col-sm-1" style="color: lightgrey;">
      	<%= obs.id %>
					<% if obs.issues.where("resolved != ?", true).present? %>
	  				<span data-toggle="tooltip" data-placement="top" title="Issue reported">
  						<%= link_to "", observation_path(obs), class: "glyphicon glyphicon-warning-sign", style: "color:red;"  %>
  					</span>
					<% end %>
      </div>

			<div class="col-sm-3">

				<div class="col-sm-2">
  				<% if !obs.user_id.blank? && obs.user_id != 0 %>
		  			<span data-toggle="tooltip" data-placement="top" title="Contributor">
	  					<%= link_to "", user_path(obs.user_id), class: "glyphicon glyphicon-user" %>
	  				</span>
  				<% end %>
  			</div>

				<div class="col-sm-2">
  				<% if !obs.location_id.blank? && obs.location_id != 0 %>
  				  <% if obs.location_id == 1 %>
		  				<span data-toggle="tooltip" data-placement="top" title="Global estimate">
				      	<%= link_to "", location_path(obs.location_id), class: "glyphicon glyphicon-globe", 'data-no-turbolink' => true %>
	  					</span>
	  				<% else %> 
		  				<span data-toggle="tooltip" data-placement="top" title="Location specific estimate">
	  			      <%= link_to "", location_path(obs.location_id), class: "glyphicon glyphicon-map-marker", 'data-no-turbolink' => true %>
	  					</span>
  				  <% end %> 
  				<% end %> 
  			</div>

				<div class="col-sm-2">
  				<% if !obs.resource_id.blank? && obs.resource_id != 0 %>
	  				<span data-toggle="tooltip" data-placement="top" title="Primary resource">
	  					<%= link_to "", resource_path(obs.resource_id), class: "glyphicon glyphicon-tag" %>
  					</span>
  				<% end %> 
  			</div>    

				<div class="col-sm-2">
  				<% if !obs.resource_secondary_id.blank? %>
	  				<span data-toggle="tooltip" data-placement="top" title="Secondary resource">
	  					<%= link_to "", resource_path(obs.resource_secondary_id), class: "glyphicon glyphicon-tags" %>
  					</span>
  				<% end %> 
  			</div>    

				<div class="col-sm-2">
	      	<% if obs.measurements.size > 1 %>
	  				<span data-toggle="tooltip" data-placement="top" title="Context included">
  						<%= link_to "", observation_path(obs), class: "glyphicon glyphicon-eye-open" %>
  					</span>
					<% end %>
  			</div>

				<div class="col-sm-2">
	      	<% if obs.approval_status == "pending" %>
	  				<span data-toggle="tooltip" data-placement="top" title="Pending">
  						<%= link_to "", observation_path(obs), class: "glyphicon glyphicon-asterisk" %>
  						</span>
					<% end %>
  			</div>

			</div>


      <% if @trait %>
      	<% measurements = obs.measurements %>
			<% else %> 
      	<% measurements = obs.measurements.joins(:trait).where("trait_class NOT LIKE ?", "Contextual") %>
			<% end %> 

    	<% if measurements.size == 1 %>
				<div class="col-sm-3">
					<%= link_to measurements.first.trait.trait_name, trait_path(measurements.first.trait_id), 'data-no-turbolink' => true %>
	      </div>

				<div class="col-sm-2">

          <% if measurements.first.trait.traitvalues.present? %>
            <% traitvalue = measurements.first.trait.traitvalues.where(:value_name => measurements.first.value) %>
            <% if not traitvalue.empty? and traitvalue.first.value_description.present?  %>
              <span class="label label-primary" data-toggle="tooltip" data-placement="top" title="<%= traitvalue.first.value_description %>"><%= measurements.first.value %></span>
            <% else %>
              <span class="label label-primary" data-toggle="tooltip" data-placement="top" title="No description"><%= measurements.first.value %></span>
            <% end %>
          <% else %> 
            <%= measurements.first.value %>
          <% end %> 

          <% if not measurements.first.trait.traitvalues.present? and measurements.first.standard.present? %>
            (<%= link_to measurements.first.standard.standard_unit, standard_path(measurements.first.standard_id) %>)
          <% end %>

	      </div>
    	<% else %>
      	<% if @trait %>
	      	<% measurements = measurements.joins(:trait).where("trait_name LIKE ?", @trait.trait_name) %>
 					<div class="col-sm-3">
						<%= link_to measurements.first.trait.trait_name, trait_path(measurements.first.trait_id), 'data-no-turbolink' => true %>
		      </div>

					<div class="col-sm-2">

            <% if measurements.first.trait.traitvalues.present? %>
              <% traitvalue = measurements.first.trait.traitvalues.where(:value_name => measurements.first.value) %>
              <% if not traitvalue.empty? and traitvalue.first.value_description.present?  %>
                <span class="label label-primary" data-toggle="tooltip" data-placement="top" title="<%= traitvalue.first.value_description %>"><%= measurements.first.value %></span>
              <% else %>
                <span class="label label-primary" data-toggle="tooltip" data-placement="top" title="No description"><%= measurements.first.value %></span>
              <% end %>
            <% else %> 
              <%= measurements.first.value %>
            <% end %> 

            <% if not measurements.first.trait.traitvalues.present? and measurements.first.standard.present? %>
              (<%= link_to measurements.first.standard.standard_unit, standard_path(measurements.first.standard_id) %>)
            <% end %>

		      </div>
      	<% else %>
					<div class="col-sm-5">
						<span class="label label-primary"><%= measurements.size %></span> trait measurements
		      </div>
      	<% end %>
    	<% end %>

			<div class="col-sm-2">
    		<div class="btn-group pull-right">				
					<%= link_to 'Show', observation_path(obs), class: "btn btn-xs btn-default" %>
  				<% if signed_in? && (obs.user_id == current_user.id || current_user.editor?) %>
  					<% if @pending %>
		        	<%= link_to 'Approve', observation_imports_approve_path(:item_id => obs.id), method: :post, class: "btn btn-xs btn-success" %>
		        	<%= link_to 'Reject', observation_imports_approve_path(:item_id => obs.id, :reject => true), method: :post, class: "btn btn-xs btn-danger" %> 
  					<% end %>

  				<% end %>
				</div>
			</div>
		</div>
	</li>
	<% mark = obs.specie.specie_name %>
<% end %>