config/routes.rb
Traits::Application.routes.draw do


  get '/observations/count/:model1/:itemid1', to: 'observations#count'
  get '/observations/count/:model1/:itemid1/:model2/:itemid2', to: 'observations#count'

  get '/resources/:id/doi', to: 'resources#doi'

  get '/users/:id/species', to: 'users#species'

  get '/resources/:id/duplicates', to: 'resources#duplicates'
  get '/traits/:id/duplicates', to: 'traits#duplicates', :as => :duplicates_trait
  get '/traits/:id/meta', to: 'traits#meta', :as => :meta_trait
  get '/traits/overview', to: 'traits#overview', :as => :overview_traits
  get '/traits/:id/papers', to: 'traits#resources', :as => :resources_trait
  # match '/meta/:id',     to: 'static_pages#show',    via: 'get', :as => :show_meta

  match '/resources/:id/expunge',     to: 'resources#expunge',    via: 'get', :as => :expunge_resource
  match '/resources/:id/update',     to: 'resources#update',    via: 'get', :as => :update_resource

  resources :duplicates 

  resources :releases

  # resources :observations do
  #   resources :issues
  # end

  get 'password_resets/new'

  match '/observation_imports/approve', to: 'observation_imports#approve', via: ['get', 'post'] , :as => :observation_imports_approve

  #get '/imports/show', to: 'imports#show', :as => :show_imports
  # match '/imports/approve', to: 'imports#approve', via: ['get', 'post'] , :as => :approve
  match '/imports/:name', to: 'imports#create', :via => :post, :as => :upload
  get '/imports/:name', to: 'imports#new'
  
  match '/search/json_completion', to: 'search#json_completion', via: 'get', as: 'json_completion'
  
  resources :imports
  resources :search 
  resources :synonyms

  
  get '/history', to:'versions#index'
  get '/history/:version_id', to: 'versions#show'
  post '/revert/:version_id', to: 'versions#revert_back'
  get '/species/:id/resources', to: 'species#show'
  get '/traits/:id/resources', to: 'traits#show'
  get '/locations/:id/resources', to: 'locations#show'
  get '/resources/:id/resources', to: 'resources#show'
  get '/releases/:id/resources', to: 'releases#show'

  
  get '/resources/status', to: 'resources#status'

  # match '/duplicate/:id',     to: 'static_pages#duplicate',    via: 'get', :as => :duplicate_meta
# get '/meta/:ids', to: 'static_pages#show'

  
  resources :imports

  resources :methodologies
  post '/methodology/:id/trait', to: 'methodologies#remove_trait', :as => :remove_methodology_trait
  resources :methodologies do
    post :export, :on => :collection
  end

  resources :password_resets

  resources :species do
    post :export, :on => :collection
  end

  resources :species do
    resources :traits do
      resources :users
    end
  end

  resources :locations do
    post :export, :on => :collection
  end

  resources :resources do
    post :export, :on => :collection
  end

  
  resources :standards do
    post :export, :on => :collection
  end

  resources :measurements 

  resources :issues

  resources :observation_imports

  resources :observations do  
    resources :issues

      post :update_multiple, :on => :collection
      # get :autocomplete_location_name, :on => :collection
      # get :autocomplete_specie_name, :on => :collection
      # get :autocomplete_resource_author, :on => :collection

      get :update_values, :on => :collection
      get :update_values, :on => :member
      get :update_random, :on => :collection
      get :update_random, :on => :member

  end

  #match ':controller(/:action(/:id))', via: 'get'

  # resources :users do
  #   resources :traits
  # end
  
  resources :traits do

    post :export, :on => :collection
  end

  resources :entities

  resources :users do  
      post :update_multiple, :on => :collection
  end
  
  resources :sessions,      only: [:new, :create, :destroy]


  root to: 'static_pages#home'
  match '/signup',      to: 'users#new',            via: 'get'
  match '/signin',      to: 'sessions#new',         via: 'get'
  match '/signout',     to: 'sessions#destroy',     via: 'delete'

  match '/meta',        to: 'static_pages#meta',    via: 'get'
  match '/release',        to: 'static_pages#release',    via: 'get'
  match '/uploads',        to: 'static_pages#uploads',    via: 'get'

  match '/test',  to: 'static_pages#test',   via: 'get'
  match '/procedures',  to: 'static_pages#procedures',   via: 'get'
  match '/editors',     to: 'static_pages#editors',   via: 'get'
  match '/contributors', to: 'static_pages#contributors',   via: 'get'
  match '/download',    to: 'static_pages#download',   via: 'get'
  match '/bulk_import', to: 'static_pages#bulk_import',   via: 'get'
  match '/documentation',    to: 'static_pages#documentation',   via: 'get'

  match '/export_specie_trait', to: 'static_pages#export_specie_trait',   via: 'get'
  match '/export_location_trait', to: 'static_pages#export_location_trait',   via: 'get'
  match '/export_ready_trait', to: 'static_pages#export_ready_trait',   via: 'get'

  match '/export_release_resources', to: 'static_pages#export_release_resources',   via: 'get'
  match '/export_release', to: 'static_pages#export_release',   via: 'get'

  match '/doi_new',    to: 'resources#doi_new',   via: 'get'


  # dynamic pull-down for trait select
  # match '/update_values', to: 'measurements#update_values', via: 'get'
  

end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>

	<%= render 'shared/error_messages', object: @resource %>

  <p>Enter a doi OR the full details below the line if a doi is not available. If you enter a doi, the details below the line will be overwritten with the resource details extracted from Crossref.</p>

  <div class="form-group">
    <%= f.label :doi %>
    <p><small>Only the identifier part (e.g., 10.1007/s00338-014-1248-9). Do not append text like "DOI:"</small></p>
    <%= f.text_field :doi_isbn, :placeholder => "Preferred...", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :resource_type %>
    <p><small>Required if there is no doi available (e.g., if a book or website)</small></p>
    <%= f.select :resource_type, ['', 'paper', 'paper_without_doi', 'monograph', 'book', 'book_chapter', 'webpage', 'CD_rom', 'conference_proceedings', 'thesis', 'technical_report', 'petition', 'pers_obs', 'pers_comm', 'opinion'], {:selected => @resource.resource_type}, class: "form-control" %>
  </div>  

  <div class="form-group">
    <%= f.label :resource_notes %>
    <%= f.text_area :resource_notes, class: "form-control" %>
  </div>

  <div class="form-group">
    <% if current_user.admin? %>
      <%= f.label :enterer %>
      <% if f.object.id.present? %>
        <%= f.select :user_id, User.where(:contributor => true).collect {|a| ["#{a.name} #{a.last_name}", a.id]}, {}, class: "form-control" %>
      <% else %>
        <%= f.select :user_id, User.where(:contributor => true).collect {|a| [a.name, a.id]}, {:selected => current_user.id}, class: "form-control" %>
      <% end %>
    <% else %>
      <%#= current_user.name %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
    <% end %>
  </div>

  <% if current_user.editor? %>
    <div class="form-group">
      <%= f.label :status %>
      <%= f.select :approval_status, ["", "pending", "approved"], {}, class: "form-control" %>
    </div>
  <% end %>

  <%= f.submit "Submit", class: "btn btn-primary btn-lg" %>

  <hr>
  <h3>Details (if no doi)</h3>

  <p><label class="label label-danger">Warning</label> If you entered a valid doi above, the fields below will automatically be overwritten.</p>

	<div class="form-group">
		<%= f.label "Author/s" %>
		<p><small>For example, "Jones A. S., Smith T. R." without using "and" or "&"</small></p>
		<%= f.text_field :author, :placeholder => "Required...", class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :year %>
		<%= f.text_field :year, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :title %>
		<p><small>Without a period at the end</small></p>
		<%= f.text_field :title, :placeholder => "Required...", class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label "Journal or Publisher" %>
		<p><small>Full name or abbreviation without periods.</small></p>
		<%= f.text_field :journal, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label "Volume and pages or website url" %>
		<p><small>For example, "23, 135-156"</small></p>
		<%= f.text_field :volume_pages, class: "form-control" %>
	</div>


	<%= f.submit "Submit", class: "btn btn-primary btn-lg" %>

<% end %>

app/views/resources/duplicates.html.erb
<% provide(:title, 'Duplicates') %>

<div class="col-sm-12">

  <h3>

      <p>
        <%= @resource.author %>
        <% if @resource.year %>
          (<%= @resource.year %>)
        <% end %>
        <%= @resource.title %>.
        <% if @resource.journal %>
          <em><%= @resource.journal %></em>
        <% end %>
        <% if @resource.volume_pages %>
          <%= @resource.volume_pages %>
        <% end %>
      </p>

    <% if @resource.approval_status == "pending" %>
      <span class="label label-danger pull-right">pending approval</span>
    <% end %>
  </h3>
  <hr>

  <p>
    <%= link_to 'Back', @resource, class: "btn btn-xs btn-default" %>
  </p>

  <p>
    
  </p>

  <p>
    <span class="label label-warning"><%= @duplicates.length %></span> potential duplicate records have been detected for this resource. Detection occurs when an observation occurs of the same species, resource and location with the same measured trait, standard and value. Duplicates might be legitimate.
  </p>

  <% if @duplicates %>
    <% @duplicates.order(:specie_id).each do |dup| %>

      <ul class="list-group">
        <li class="list-group-item">             
          <div class="row">
            <div class="col-sm-2">
              <em><%= link_to Specie.select(:specie_name).find_by_id(dup.specie_id).specie_name, specie_path(dup.specie_id) %></em>
            </div>
            <div class="col-sm-2">
              <%= link_to Trait.select(:trait_name).find_by_id(dup.trait_id).trait_name, trait_path(dup.trait_id) %>
            </div>
            <div class="col-sm-2">
              <%= dup.value %>
            </div>
            <div class="col-sm-2">
              <% standard = Standard.select(:standard_name, :standard_unit).find_by_id(dup.standard_id) %>
              <%= link_to standard.standard_unit, standard_path(dup.standard_id) %> (<%= standard.standard_name %>)
            </div>
            <div class="col-sm-2">
              <% dup.ids.each do |id| %>
                <p><%= link_to id, observation_path(id), class: "btn btn-default btn-xs" %></p>
              <% end %>
            </div>
            <div class="col-sm-2">
              <%= link_to "Show", specie_trait_path(dup.specie_id, dup.trait_id), class: "btn btn-default btn-xs" %></p>
            </div>
          </div>

        </li>
      </ul>
    <% end %>
  <% else %>
    None
  <% end %>
  
</div>

app/views/resources/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1>Editing resource</h1>

    <% if (@sug and not @sug == "Invalid") and (@resource.resource_type == "paper" or @resource.resource_type.blank?) %>
      <ul class="list-group">
        <li class="list-group-item">              
          <p>
            <strong>Suggested doi from CrossRef based on title:</strong>
            <ul>
            <% @sug["message"]["items"].each do |a| %>
              <li><%= a["DOI"] %> <small>(<%= link_to a["title"][0], "http://dx.doi.org/" + a["DOI"], :target => "_blank" %>)</small></li>
            <% end %>
            </ul>
          </p>
        </li>
      </ul>
    <% end %>

    <% if not @resource.doi_isbn.present? and (@resource.resource_type == "paper" or @resource.resource_type.blank?) %>
      <ul class="list-group">
        <li class="list-group-item">              
          <strong>Suggested doi from CrossRef based on title:</strong>
          <ul id="doilist">
            <li><span class="doi" data-resourceid=<%= @resource.id %>><span class="glyphicon glyphicon-refresh spinning"></span></span></li>
          </ul>
        </li>
      </ul>
    <% end %>



		<%= render 'form' %>

		<%= link_to 'Show', @resource %> |
		<%= link_to 'Back', resources_path %>

	</div>
</div>

app/views/resources/index.html.erb
<% provide(:title, 'Resources') %>

<div class="col-md-9">
  <%= render "shared/index_header" %>
</div>

<%= form_tag export_resources_path do %>

  <div class="col-md-3">
    <%= render "shared/download_options" %>
  </div>

  <div class="col-sm-12">
    
    <%= will_paginate @resources, :inner_window => 1, :outer_window => 0 %>

		<ul class="list-group">
    	<% @resources.each do |resource| %>
			  <li class="list-group-item">							
					<div class="row">
		        <div class="col-sm-1" style="color: lightgrey;">
		        	<%= resource.id %>
							<% if resource.approval_status == 'pending' %>
								<span class="glyphicon glyphicon-warning-sign"  style="color:red;" title="Pending Approval"></span>
							<% end %>
		        </div>

		        <div class="col-sm-7">
		        	<%= link_to resource.author.html_safe, resource %>
		        	<% if resource.year %>
			        	(<%= resource.year %>)
	    				<% end %>		
		        	<%= resource.title %>.
              <% if resource.journal %>
                <em><%= resource.journal %></em>
              <% end %>   
              <% if resource.volume_pages %>
                <%= resource.volume_pages %>
              <% end %>   
		        </div>

            <div class="col-sm-2">
              <% if signed_in? && current_user.contributor? and not params[:all] %>
                <div id="dupdetect">
                  <p>
                    <span class="dup" data-resourceid=<%= resource.id %>><span class="label label-warning"><span class="glyphicon glyphicon-refresh spinning"></span></span></span>
                  </p>
                </div>
              <% end %>
            </div>


            <% if not params[:all] %>
              <div id="countlist" class="col-sm-2">
                <p class="pull-right">
                  <%= render "shared/access_counts", :itemid1 => resource.id %>
                  <%= check_box_tag "checked[]", resource.id %>
                </p>
              </div>
            <% else %>
              <div class="col-sm-2">
                <p class="pull-right">
                  <%= check_box_tag "checked[]", resource.id %>
                </p>
              </div>
            <% end %>

					</div>
				</li>
	    <% end %>		
    </ul>
    
    <%= will_paginate @resources, :inner_window => 1, :outer_window => 0 %>
	</div>
<% end %>


<% if @resources.blank? %>
  <div class="col-md-12">
    <%= render "shared/no_observations" %>
  </div>
<% end %>

<div class="col-sm-12">
  <p>Download full resources list as a <%= link_to "csv", resources_path(format: "csv", search: params[:search], page: params[:page], all: params[:all], count: params[:count]) %>.</p>
</div>

app/views/resources/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1>New resource</h1>

    <p><label class="label label-danger">Warning</label> Have you determined that the resource (paper) you are about to enter does not already exist? Try searching for the paper name or title (above) to ensure it doesn't already exist.</p>

		<%= render 'form' %>

		<%= link_to 'Back', resources_path %>

	</div>
</div>

app/views/resources/show.html.erb
<% provide(:title, "Resource") %>

<div class="col-md-12">
  <h3>

			<p>
			  <%= @resource.author.html_safe %>
				<% if @resource.year %>
			  	(<%= @resource.year %>)
				<% end %>
			  <%= @resource.title.html_safe %>.
				<% if @resource.journal %>
			  	<em><%= @resource.journal %></em>
				<% end %>
				<% if @resource.volume_pages %>
			  	<%= @resource.volume_pages %>
				<% end %>
			</p>

		<% if @resource.approval_status == "pending" %>
			<p>
				<span class="label label-danger pull-right">pending approval</span> 
			</p>
		<% end %>

  </h3>
</div>

<div class="col-md-6">
  <p>
    <strong>ID:</strong>
    	<%= @resource.id %>
  </p>

	<p>
	  <strong>DOI:</strong>
		<% if @resource.doi_isbn.present? %>
	  	<%= link_to @resource.doi_isbn, "http://dx.doi.org/" + @resource.doi_isbn, :target => "_blank" %>
		<% elsif @resource.resource_type == "paper" or @resource.resource_type.blank? %>
			<span class="label label-danger">not added</span>
		<% else %>
			<span class="label label-success"><%= @resource.resource_type %></span>
		<% end %>
	</p>

  <%= render "shared/description", :description => @resource.resource_notes %>

	<p>
    <div class="btn-group">
      <%= link_to 'Back', resources_path, class: "btn btn-xs btn-default" %>
      <% if signed_in? && current_user.contributor? %>
        <%= link_to 'Edit', edit_resource_path(@resource), class: "btn btn-xs btn-default" %>
      <% end %>
    </div>
    <% if signed_in? && current_user.admin? %>
      <div class="btn-group pull-right">
        <%= link_to 'Delete', @resource, method: :delete, data: { confirm: 'Delete entire resource, including observations and measurements?' }, class: "btn btn-xs btn-danger" %>
        <%= link_to 'Expunge', expunge_resource_path(@resource), data: { confirm: 'Delete all associated observations and measuerments for this resource?' }, class: "btn btn-xs btn-warning" %>
        <%= link_to 'Update', update_resource_path(@resource), class: "btn btn-xs btn-success" %>
      </div>
    <% end %>
	</p>

</div>


<% if not @locations.empty? and not @locations.map(&:id).include? 1 %>
  <div class="col-md-6" data-no-turbolink>
    <ul class="list-group">
    <li class="list-group-item">              
    <div id="map" data-no-turbolink></div> 
    </li>
    </ul>
  </div>
<% end %>

<div class="col-md-12">

	<h3>Observations from this resource</h3>

  <% if signed_in? && current_user.contributor? %>
    <div id="dupdetect">
    <p>
      <span class="dup" data-resourceid=<%= @resource.id %>></span>
    </p>
    </div>
  <% end %>

	<ul class="nav nav-tabs">
		<% if params[:secondary] %>
			<% @observations = @secondary %>
		  <li role="presentation"><%= link_to 'Primary', resource_path(@resource) %></li>		
		  <li role="presentation" class="active"><%= link_to 'Secondary', resource_path(@resource, secondary: true) %></li>
	  <% else %>
			<% @observations = @primary %>
		  <li role="presentation" class="active"><%= link_to 'Primary', resource_path(@resource) %></li>		
		  <li role="presentation"><%= link_to 'Secondary', resource_path(@resource, secondary: true) %></li>
		<% end %>
	</ul>

	<br>

	<% if @observations.empty? %>
		<%= render "shared/no_observations" %>
	<% else %>
		<%= will_paginate @observations, :inner_window => 1, :outer_window => 0 %>
		<%= render "shared/observations" %>
		<br>
		<%= will_paginate @observations, :inner_window => 1, :outer_window => 0 %>
	<% end %>  

</div>

<script>
  function initMap() {
    var locations = <%= raw @locations.map {|i| [i.location_name.to_s, i.latitude.to_s, i.longitude.to_s, i.id.to_s] } %>;


    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 1,
      center: new google.maps.LatLng(0, 155),
      mapTypeId: google.maps.MapTypeId.SATELLITE,
      streetViewControl: false
    });

    var opt = { maxZoom: 13 };
    map.setOptions(opt);

    var infowindow = new google.maps.InfoWindow();

    var marker, i;
    var bounds = new google.maps.LatLngBounds();

    for (i = 0; i < locations.length; i++) {  
      
      var content = '<a data-no-turbolink="true" href="/locations/'+locations[i][3]+'">'+locations[i][0]+'</a>';
      
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map
      });

      bounds.extend(marker.getPosition());

      google.maps.event.addListener(marker, 'click', function(marker, content) {
        return function() {
          infowindow.setContent(content);
          infowindow.open(map, marker);
        }
      }(marker, content));

    }
    map.fitBounds(bounds);
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBJG1Hc3Z4RxhlbmvsHvzXakd_pCZjD_5I&callback=initMap" async defer></script>

app/views/resources/status.html.erb
<% provide(:title, 'Resources issues') %>


<div class="page-header">
  <h1>
  	Resources <font style="color:red;">Errors</font>
		<% if signed_in? && current_user.admin? %>	
			<%= link_to 'Back', resources_path, class: "btn btn-default pull-right" %>
		<% end %>
	</h1>
</div>

<p>The following resources have problems that need fixing.</p>


<h3>DOI missing</h3>

<%= will_paginate @resources, :inner_window => 1, :outer_window => 0 %><br><br>

<div class="row">
  <div class="col-sm-12">
		<ul class="list-group">
    	<% @resources.each do |resource| %>

		    <% if resource.doi_isbn.present? %>
		      <% begin %>
		        <% @doi = JSON.load(open("https://api.crossref.org/works/#{resource.doi_isbn}")) %>
		        <% if @doi["message"]["author"][0]["family"] == "Peresson" %>
		          <% @doi = "Invalid" %>
		        <% end %>
		      <% rescue %>
		        <% @doi = "Invalid" %>
		      <% end %>
		    <% else %>
		      <% begin %>
		        <% @sug = JSON.load(open("https://api.crossref.org/works?query=#{resource.title.tr(" ", "+")}&rows=1")) %>
		      <% rescue %>
		        <% @sug = "Invalid" %>
		      <% end %>
		    <% end %>


			  <li class="list-group-item">							
					<div class="row">
		        <div class="col-sm-1" style="color: lightgrey;">
		        	<%= resource.id %>
		        </div>

		        <div class="col-sm-5">
		        	<%= link_to resource.author, resource %>
		        	<% if resource.year %>
			        	(<%= resource.year %>)
	    				<% end %>		
		        	<small><%= resource.title %></small>
		        	<br>
							<% if resource.doi_isbn.present? %>
						  	<%= link_to resource.doi_isbn, "http://dx.doi.org/" + resource.doi_isbn, :target => "_blank" %>
								<% if @doi == "Invalid" %>
									<span class="label label-danger">invalid (or the crossref server is down)</span>
								<% end %>
							<% else %>
								<span class="label label-danger">not added</span>
							<% end %>
							
							<% if @sug and not @sug == "Invalid" %>
							  <p>
								  <strong>Suggested DOI based on title:</strong>
								  <ul>
							    <% @sug["message"]["items"].each do |a| %>
							      <li><%= a["DOI"] %> <small>(<%= link_to a["title"][0], "http://dx.doi.org/" + a["DOI"], :target => "_blank" %>)</small></li>
							    <% end %>
							    </ul>
							  </p>
							<% end %>

		        </div>

					 	<div class="col-sm-1">
							<%= check_box_tag "checked[]", resource.id %>
						</div>

						<div class="col-sm-2">
							<% if not params[:all] %>
			        	<%#= render "shared/access_counts", :acc => Observation.where(:resource_id => resource) %>
							<% end %>
							<% if resource.approval_status == 'pending' %>
								&nbsp;	<span class="glyphicon glyphicon-floppy-remove"  style="color:red;text-align:center;" title="Pending Approval"></span>
							<% end %>
						</div>

		        <div class="col-sm-3">
					    <div class="btn-group pull-right">
					     	<%= link_to 'Show', resource_path(resource), class: "btn btn-xs btn-default" %>
							  <% if signed_in? && current_user.editor? %>
				        	<%= link_to 'Edit', edit_resource_path(resource), class: "btn btn-xs btn-default" %>
								<% end %>
							  <% if signed_in? && current_user.admin? %>
				        	<%= link_to 'Delete', resource, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %>
								<% end %>
			        </div>
						</div>
					</div>
				</li>
	    <% end %>		
    </ul>
	</div>
</div>

<%= will_paginate @resources, :inner_window => 1, :outer_window => 0 %><br><br>


<% if @resources.blank? %>
  <div class="alert alert-danger" role="alert">No resource issues to report.</div>
<% end %>